theme: jekyll-theme-midnight
title: MK3SL Homepage
description: Mksipe Shell Script Library
safe: BOOL
timezone: central
encoding: UTF-8
show_downloads: true
author: Mason Sipe
minimal_mistakes_skin: "contrast"
repository: "mksipe/Shell-Script-Lib"
search: true
images: true
