theme: jekyll-theme-midnight
title: MK3SL Homepage
description: MK3SL is a resource repository that you can use at your disposal. It was made to help keep your system secure while being able to maintain tools that can be useful to developing in other scripts.
safe: BOOL
timezone: central
encoding: UTF-8
show_downloads: true
author: Mason Sipe
minimal_mistakes_skin: "contrast"
repository: "mksipe/Shell-Script-Lib"
search: true
