version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date && apt install git -y 
      - run:
          name: Initialize program
          command: git clone https://github.com/mksipe/Shell-Script-Lib && cd Shell-Script-Lib && chmod 755 INITAILIZE.sh && ./INITIALIZE.sh && cd /bin/lib/sh/MK3S && ./RecSetup.sh
